import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./styles/layout.css";
import "./styles/layout/header.css";
import "./styles/layout/footer.css";
import "./styles/layout/mission.css";
import Footer from "@/app/components/Footer";
import Header from "@/app/components/Header";
import MissionBaneer from "./components/ui/MissionBaneer";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Projet Louis Braille",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} body`}>
        <Header />
        <main>
            {children}
            <MissionBaneer />
        </main>
        <Footer />
        </body>
        </html>
    );
}